animation:
  Dungeon Meshi:
    blacklist: false
    episode: 24,23,22,21,20,19,18,17,16,15,14,13,10,09,07,06,05,04,03,02,01
    whitelist: Dungeon Meshi,迷宫饭
  GIRLS BAND CRY:
    blacklist: 繁
    episode: 1,2,3,4,5,6
    whitelist: GIRLS BAND CRY,哭泣少女乐队
  吹响吧! 上低音号 第三季:
    blacklist: 繁
    episode: 1,2,3,4
    whitelist: 吹响,Euphonium,Hibike,上低音号,悠风号
aria2:
  log: /tmp/aria2.log
  path: ./
  port: 6800
  secret: LoongLit
  server: localhost
