#!/bin/bash

HOME=$1 && CONF="${HOME}/perform_config.conf"

# 获取多项配置
function get_config_multiple () {
    local section=$1 key=$2
    val=$(awk -F '=' '/\['$section'\]/{a=1}a==1&&$1~/'$key'/{print $2;exit}' "$CONF")
    echo "${val}"
}

# 获取单项配置
function get_config() {
    local key=$1
    sed -n 's/^[[:space:]]*'$key'[[:space:]]*=[[:space:]]*\(.*[^[:space:]]\)\([[:space:]]*\)$/\1/p' $CONF
}

# 获取全部任务名称
function get_task_name() {
    task_name=$(cat "$CONF" | grep "\\[task.*\\]" | grep -oP "[a-z]*\d+")
    echo "${task_name}"
}


LOG_FILE="$(get_config_multiple main log_file)"
# 打印日志
function LOG() {
    local content=$1 title=$2 logdate && logdate=$(date "+%Y-%m-%d %H:%M:%S")
    echo -e "\e[32m${logdate}\e[0m>>> ${title} ${content}" | tee -a "$LOG_FILE"
}

RCLONE_CONFIG="$(get_config_multiple rclone config)"
# 上传文件至 rclone
function UPLOAD() {
    local mode=$1 source=$2 target=$3
    rclone -vP $mode "$source" "$target" --log-file="$LOG_FILE" --config="$RCLONE_CONFIG"
}

# 对字符串进行 16 进制编码
function URLENCODE() {
  local length="${#1}"
  for (( i = 0; i < length; i++ )); do
    local c="${1:i:1}" # 从左边第 i 个位置开始, 截取一个字符
    case $c in # 排除 字母 数字 和部分特殊字符
      [a-zA-Z0-9.~_-//:]) printf "$c" ;;
    *) printf "$c" | xxd -p -c1 | while read x;do printf "%%%s" "$x";done
  esac
done
}


# cat $cba_ini | # 打印文件
#   grep "\\[taks.*\\]" | # 匹配 前缀为 taks的名称
#   grep -oP "[a-z]*\d+" # 去掉方括号
#   sort -r | # 按照 降序排序
#   awk "{print $1}" | 
#   head -1  # 获取第一行的字符串, 并进行打印

