#!/bin/bash

# HOME=$(dirname "$(realpath -es "$0")")
HOME=$1
conf="${HOME}/upload_and_scrape.conf"

# 获取多项配置
function get_config_multiple () {
    local file="$conf"; local section=$1 key=$2
    val=$(awk -F '=' '/\['$section'\]/{a=1}a==1&&$1~/'$key'/{print $2;exit}' "$file")
    echo "${val}"
}

# 获取单项配置
function get_config() {
    local file="$conf"
    local key=$1
    sed -n 's/^[[:space:]]*'$key'[[:space:]]*=[[:space:]]*\(.*[^[:space:]]\)\([[:space:]]*\)$/\1/p' $file
}

# 获取全部任务名称
function get_task_name() {
    # shellcheck disable=SC2002

    val=$(cat "$conf" | grep "\\[task.*\\]" | grep -oP "[a-z]*\d+")
    echo "${val}"
}

function main_config() {
  get_config_multiple main "$1"
}

temporary_folder="$(main_config temporary_folder)"
buffer_folder="$(main_config buffer_folder)"
log_level="$(main_config log_level)"
log_file="${temporary_folder}/aria2.log"


# 打印日志
function log() {
    
    local content=$1 code=$2
    local logdate
    logdate=$(date "+%Y-%m-%d %H:%M:%S")
    case "$code" in
        "" ) color="";; 0 ) color="\e[32m[info]\e[0m" ;; 1 ) color="\e[32m[debug]\e[0m" ;;
    esac

    echo -e "${logdate}>>>${color} ${content}" | tee -a "$log_file"
}

function LOG_INFO() {
  local content=$1; log "$content" 0
}

function LOG_DEBUG() {
  if [[ $log_level = debug ]]; then local content=$1; log "$content" 1; else 0;fi
}


# cat $cba_ini | # 打印文件
#   grep "\\[taks.*\\]" | # 匹配 前缀为 taks的名称
#   grep -oP "[a-z]*\d+" # 去掉方括号
#   sort -r | # 按照 降序排序
#   awk "{print $1}" | 
#   head -1  # 获取第一行的字符串, 并进行打印

