#!/bin/bash

HOME=$(dirname "$(realpath -es "$0")")
conf="${HOME}/rss_and_upload_and_scrape.conf"

# 获取多项配置
function get_config_multiple () {
    local file section key
    file="$conf"
    section=$1
    key=$2
    # shellcheck disable=SC2086
    val=$(awk -F '=' '/\['${section}'\]/{a=1}a==1&&$1~/'${key}'/{print $2;exit}' $file)
    echo "${val}"
}

# 获取单项配置
function get_config() {
    local file="$conf"
    local key=$1
    sed -n 's/^[[:space:]]*'$key'[[:space:]]*=[[:space:]]*\(.*[^[:space:]]\)\([[:space:]]*\)$/\1/p' $file
}

# 获取全部任务名称
function get_task_name() {
    # shellcheck disable=SC2002

    val=$(cat "$conf" | grep "\\[task.*\\]" | grep -oP "[a-z]*\d+")
    echo "${val}"
}

# 打印日志
function log() {
    local file=$1
    local text=$2
    local code=$3
    local logdate
    logdate=$(date "+%Y-%m-%d %H:%M:%S")
    case "$code" in
        "" ) color="";;
        0 ) color="\e[32m成功 \e[0m" ;;
        1 ) color="\e[32m警告 \e[0m" ;;
        2 ) color="\e[33m失败 \e[0m" ;;

    esac
    echo -e "${logdate}>>>${color} ${text}" | tee -a "$file"
}

function get_log_path() {
#获取 log 地址
    log_path=$(get_config_multiple "$1" log)
    echo "$log_path"
}

function rlog() {
# 打印 rss 订阅日志
    log "$(get_log_path rss)" "$1" "$2"
}

function alog() {
# 打印 aria2 日志
    log "$(get_log_path aria2)"  "$1" "$2"
}
function ulog() {
# 打印 上传日志 日志
    log "$(get_log_path upload)"  "$1" "$2"
}

function md5() {
# 计算md5
    echo -n "$1" | md5sum | cut -d " " -f1
}
 
function copyto() {
# 通过 rclone 将文件传输到 网盘中
    local source=$1
    local target
    local log
    target="$(get_config_multiple rclone name):$1"
    log=$(get_log_path rclone)
    rclone copyto -v "$source" "$target" --log-file="$log"
 }

# 对字符串进行 16 进制编码
function urlencode() {
  local length="${#1}"
  for (( i = 0; i < length; i++ )); do
    local c="${1:i:1}"
    case $c in
      [a-zA-Z0-9.~_-]) printf "$c" ;;
    *) printf "$c" | xxd -p -c1 | while read x;do printf "%%%s" "$x";done
  esac
done
}

function curl_get() {

    local url=$1
    local headers
    headers="Authorization: Bearer $(printenv tmdb_auth)"

    curl --request GET --url "$url" --header "$headers"

}

    



# cat $cba_ini | # 打印文件
#   grep "\\[taks.*\\]" | # 匹配 前缀为 taks的名称
#   grep -oP "[a-z]*\d+" # 去掉方括号
#   sort -r | # 按照 降序排序
#   awk "{print $1}" | 
#   head -1  # 获取第一行的字符串, 并进行打印

